// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0s6icGa-v6_xhVIawbSuyoJ-z3ObNB0',
    appId: '1:330481800405:web:755b1596d91af72d887e5c',
    messagingSenderId: '330481800405',
    projectId: 'my-app-766dc',
    authDomain: 'my-app-766dc.firebaseapp.com',
    storageBucket: 'my-app-766dc.firebasestorage.app',
    measurementId: 'G-3KQQDN0T7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCopYshbWF4Viqbt-DpaE40uXZvdH0CE3U',
    appId: '1:330481800405:android:17ea4070fe2fd354887e5c',
    messagingSenderId: '330481800405',
    projectId: 'my-app-766dc',
    storageBucket: 'my-app-766dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyLBhyael1v2faCt-Rwk8B8-nZOxZ_v8',
    appId: '1:330481800405:ios:163b0267c82ad8ba887e5c',
    messagingSenderId: '330481800405',
    projectId: 'my-app-766dc',
    storageBucket: 'my-app-766dc.firebasestorage.app',
    androidClientId: '330481800405-sbh0s9qi7g6e8udhgnh6bmepa0fo8e39.apps.googleusercontent.com',
    iosClientId: '330481800405-u3282icfepg6su08f7r8los6uosnuncf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyLBhyael1v2faCt-Rwk8B8-nZOxZ_v8',
    appId: '1:330481800405:ios:163b0267c82ad8ba887e5c',
    messagingSenderId: '330481800405',
    projectId: 'my-app-766dc',
    storageBucket: 'my-app-766dc.firebasestorage.app',
    androidClientId: '330481800405-sbh0s9qi7g6e8udhgnh6bmepa0fo8e39.apps.googleusercontent.com',
    iosClientId: '330481800405-u3282icfepg6su08f7r8los6uosnuncf.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0s6icGa-v6_xhVIawbSuyoJ-z3ObNB0',
    appId: '1:330481800405:web:3b9f496929afe652887e5c',
    messagingSenderId: '330481800405',
    projectId: 'my-app-766dc',
    authDomain: 'my-app-766dc.firebaseapp.com',
    storageBucket: 'my-app-766dc.firebasestorage.app',
    measurementId: 'G-D82NNBRYY1',
  );
}
